src/components/common/Button.tsx
src/components/common/Footer.tsx
src/components/common/Header.tsx
src/components/common/Input.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
resolves #5

🎉 init: 폴더구조 추가

---

package-lock.json
package.json

📝 docs: , 추가

---

src/app/recipe/RecipeList.tsx
src/app/recipe/page.tsx
src/app/recipe/search/RecipeSearch.tsx
src/app/recipe/search/[ingredient]/page.tsx
src/app/recipe/write/page.tsx
src/components/common/Input.tsx

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 레시피 작성 페이지  UI
- 레시피 관련 페이지 공백div 제거 / padding 추가
- Input 컴포넌트 수정
resolves #47

✨ feat: 레시피 작성 페이지 UI

---

src/app/recipe/RecipeCarousel.tsx
src/app/recipe/recipe.css
src/app/shopping/AllItemList.tsx
src/app/shopping/AllItems.tsx
src/app/shopping/HotItems.tsx
src/app/shopping/[id]/page.tsx
src/app/shopping/search/page.tsx
src/components/common/Header.tsx
src/components/common/Search.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 장보기 상품제목 가운데 정렬
- 장보기 상품 카테고리 필터링 기능 추가
- 장보기 상품 제목 1줄 처리
- 헤더 sticky 처리
- 인기 레시피 캐러셀 -> swiper로 변경
resolves #42

♻️ refactor: 장보기, 레시피, 헤더 수정

---

src/app/recipe/write/page.tsx

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #60

✨ feat: 레시피 글쓰기 페이지 수정

---

src/app/globals.css
src/components/common/Footer.tsx
src/components/common/Header.tsx
src/components/common/header.css
src/components/common/layout.css

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
footer 모바일 하단 nav바 추가
resolves #

✨ feat: footer 모바일 하단 nav바 추가

---

src/app/recipe/RecipeCarousel.tsx
src/app/recipe/RecipeList.tsx
src/app/recipe/page.tsx
src/app/recipe/search/[ingredient]/page.tsx
src/app/recipe/write/page.tsx
src/app/shopping/page.tsx
src/app/shopping/search/page.tsx
src/components/common/SearchBar.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- pages 폴더 삭제
- 루시드 아이콘으로 아이콘 이미지 교체
resolves #71

♻️ refactor: 루시드 아이콘으로 아이콘 이미지 변경

---

src/app/shopping/HotItems.tsx
src/app/shopping/[id]/page.tsx
src/components/ProductCard.tsx
src/components/common/Counter.tsx
src/components/common/Footer.tsx
src/components/common/Header.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- header 반응형 작업 
- Lucide 아이콘으로 아이콘 교체
resolves #

style: header 반응형 작업 Lucide 아이콘으로 아이콘 교체

---

src/app/mypage/buylist/BuyItem.tsx
src/app/mypage/buylist/BuyItemList.tsx
src/app/mypage/buylist/BuyList.tsx
src/app/mypage/buylist/EmptyBuyList.tsx
src/app/mypage/buylist/[_id]/BuyInfoItemList.tsx
src/app/mypage/buylist/[_id]/BuyinfoItem.tsx
src/app/mypage/buylist/page.tsx
src/app/mypage/cart/CartItemForm.tsx
src/app/mypage/cart/CartList.tsx
src/app/mypage/cart/EmptyCart.tsx
src/app/mypage/cart/page.tsx
src/app/mypage/likes/EmptyLikes.tsx
src/app/mypage/likes/LikeItemForm.tsx
src/app/mypage/likes/LikeList.tsx
src/app/mypage/likes/page.tsx
src/app/mypage/recipe/likerecipe/EmptyLikeRecipe.tsx
src/app/mypage/recipe/likerecipe/LikeRecipeItem.tsx
src/app/mypage/recipe/likerecipe/LikeRecipeList.tsx
src/app/mypage/recipe/myrecipe/EmptyMyRecipe.tsx
src/app/mypage/recipe/myrecipe/MyRecipeItem.tsx
src/app/mypage/recipe/myrecipe/MyRecipeList.tsx
src/app/order/page.tsx
src/data/actions/cart.ts
src/data/actions/post.ts
src/data/functions/post.ts
src/types/post.ts
src/types/product.ts

마이페이지 이미지 api 연결

---

src/app/mypage/layout.tsx
src/app/mypage/myuser/page.tsx
src/app/recipe/[id]/Profile.tsx
src/app/recipe/[id]/page.tsx
src/components/common/Dropdown.tsx

✨ feat: 프로필 이미지 api 연결

---

src/app/mypage/cart/CartItemForm.tsx
src/app/mypage/cart/CartList.tsx
src/app/mypage/recipe/myrecipe/MyRecipeItem.tsx
src/data/actions/cart.ts
src/types/api.ts

장바구니 수량 렌더 리팩토링

---

src/app/mypage/buylist/BuyItemList.tsx
src/app/mypage/buylist/BuyList.tsx
src/app/mypage/buylist/EmptyBuyList.tsx
src/app/mypage/buylist/Loading.tsx
src/app/mypage/buylist/[_id]/BuyInfo.tsx
src/app/mypage/buylist/[_id]/BuyInfoItemList.tsx
src/app/mypage/buylist/[_id]/Loading.tsx
src/app/mypage/cart/CartItemForm.tsx
src/app/mypage/cart/CartList.tsx
src/app/mypage/cart/EmptyCart.tsx
src/app/mypage/cart/Loading.tsx
src/app/mypage/likes/EmptyLikes.tsx
src/app/mypage/likes/LikeList.tsx
src/app/mypage/likes/Loading.tsx
src/app/mypage/myuser/page.tsx
src/app/mypage/recipe/likerecipe/EmptyLikeRecipe.tsx
src/app/mypage/recipe/likerecipe/LikeRecipeItem.tsx
src/app/mypage/recipe/likerecipe/LikeRecipeList.tsx
src/app/mypage/recipe/likerecipe/Loading.tsx
src/app/mypage/recipe/myrecipe/EmptyMyRecipe.tsx
src/app/mypage/recipe/myrecipe/Loading.tsx
src/app/mypage/recipe/myrecipe/MyRecipeList.tsx
src/components/common/Dropdown.tsx
src/data/functions/post.ts

마이페이지 스켈레톤 UI

---

api/dbinit/team/data.js
src/app/mypage/buylist/[_id]/BuyInfo.tsx
src/app/mypage/buylist/[_id]/BuyInfoItemList.tsx
src/app/order/OrderForm.tsx
src/app/order/OrderList.tsx
src/app/order/OrderUserForm.tsx
src/app/order/PayForm.tsx
src/data/actions/cart.ts
src/types/product.ts
src/types/user.ts

주문하기 폼 api 연결

---

src/app/recipe/[id]/Comment.tsx
src/app/recipe/[id]/CommentActionButton.tsx
src/app/recipe/[id]/Comments.tsx
src/app/recipe/[id]/page.tsx

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 레시피 댓글 수정/삭제 기능 구현
- 레시피 상세페이지 링크 간격 수정
resolves #133

✨ feat: 레시피 댓글 기능 구현

---

src/components/ProductCardItem.tsx

- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
찜하기 데이터 속성 옵셔널로 수정
resolves #

🐛 fix: 찜하기 데이터 속성 옵셔널로 수정

---

api/dbinit/team/data.js
src/app/layout.tsx
src/app/mypage/buylist/BuyItem.tsx
src/app/mypage/buylist/[_id]/BuyInfoItemList.tsx
src/app/mypage/buylist/[_id]/BuyinfoItem.tsx
src/app/mypage/cart/CartItemForm.tsx
src/app/mypage/layout.tsx
src/app/mypage/likes/LikeItemForm.tsx
src/app/mypage/likes/LikeList.tsx
src/app/mypage/recipe/likerecipe/LikeRecipeList.tsx
src/app/order/complete/page.tsx
src/types/product.ts

마이페이지 리팩토링

---

src/app/recipe/[id]/Comment.tsx
src/app/recipe/[id]/CommentActionButton.tsx
src/app/recipe/[id]/Comments.tsx
src/app/recipe/[id]/RecipeActionButton.tsx
src/app/recipe/[id]/edit/RecipeEditForm.tsx
src/app/recipe/write/page.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 레시피 SWAL 변경
resolves #145

♻️ refactor: 레시피 SWAL 변경

---

src/app/shopping/page.tsx

- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
빌드 에러 2차 수정 (shopping >  page.tsx에 suspense 추가)
resolves

빌드 에러 2차 수정

---

src/app/recipe/RecipeList.tsx
src/app/recipe/page.tsx
src/data/functions/post.ts

레시피 fetch 분리

---

src/app/(user)/edit/EditForm.tsx
src/app/(user)/edit/page.tsx
src/app/(user)/login/page.tsx
src/app/(user)/login/select/page.tsx
src/app/(user)/signup/SignupForm.tsx

로그인 선택/로그인/회원가입/회원정보 수정 페이지 반응형
resolves #168

Feat/login UI

---

src/app/(user)/edit/EditForm.tsx
src/app/(user)/login/LoginForm.tsx
src/app/(user)/signup/SignupForm.tsx
src/components/common/Dropdown.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #183

♻️ refactor: alert창 swal로 변경

---

src/app/order/OrderForm.tsx
src/app/order/OrderItemForm.tsx
src/app/order/OrderList.tsx
src/data/actions/cart.ts
src/data/functions/post.ts
src/types/product.ts

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
상품 상세에서 구매하기 기능 구현 완료
resolves #138

✨ feat: 상품 상세에서 구매하기 기능 구현 완료

---

src/app/mypage/layout.tsx
src/components/common/Dropdown.tsx

-  프로필 이미지 flex 수정
- 커서 포인트 추가
- 마이페이지 사이드바 로그아웃 기능 추가

✨ faet: 마이페이지 사이드바 로그아웃 기능 추가

---

src/app/recipe/RecipeList.tsx

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #192

✨ feat: 레시피 무한 스크롤, 탭 기능 구현

---

src/app/shopping/AllItems.tsx
src/app/shopping/page.tsx

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 장보기 리스트 페이지 무한 스크롤 기능 구현 완료
resolves #

✨ feat: 장보기 리스트 페이지 무한 스크롤 기능 구현 완료

---

api/dbinit/team/data.js
src/app/mypage/layout.tsx
src/app/mypage/order/[_id]/OrderInfoList.tsx
src/app/order/OrderUserForm.tsx
src/app/order/layout.tsx
src/data/actions/cart.ts
src/types/product.ts
src/types/user.ts

- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #197

판매자 메일 전송 기능

---

src/app/globals.css

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
반응형 breakpoint 수정
resolves

💄 style: 반응형 breakpoint 수정

---

src/app/recipe/RecipeList.tsx
src/app/recipe/[_id]/BookmarkButton.tsx
src/app/recipe/[_id]/RelationProducts.tsx
src/app/recipe/[_id]/page.tsx
src/app/recipe/search/[query]/page.tsx
src/app/recipe/write/RecipeWriteClient.tsx
src/app/recipe/write/page.tsx
src/components/ProductCardItem.tsx
src/data/functions/post.ts

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #203

✨ feat: 레시피 연관상품 기능 구현

---

src/app/globals.css
src/components/common/Dropdown.tsx
src/components/common/Header.tsx

헤더 드롭다운 UI 수정

---

src/app/shopping/AllItems.tsx
src/app/shopping/search/[id]/ShoppingSearchList.tsx
src/app/shopping/search/[id]/page.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
장보기 검색 결과 없는 페이지 반응형
resolves

💄 style: 장보기 검색 결과 없는 페이지 반응형

---

src/app/(user)/socialedit/SocialEditForm.tsx
src/app/(user)/socialedit/page.tsx
src/app/mypage/cart/CartList.tsx
src/app/mypage/order/OrderList.tsx
src/app/mypage/order/[_id]/OrderInfo.tsx
src/app/mypage/recipe/bookmarkRecipe/BookmarkRecipeList.tsx
src/app/mypage/recipe/myrecipe/MyRecipeList.tsx
src/app/mypage/user/Loading.tsx
src/app/mypage/user/UserInfo.tsx
src/app/mypage/wish/WishList.tsx
src/app/order/OrderForm.tsx
src/components/common/Address.tsx
src/components/common/Dropdown.tsx
src/types/product.ts

소셜 로그인 회원정보 수정 기능

---

src/app/recipe/[_id]/Comment.tsx
src/app/recipe/[_id]/Comments.tsx
src/data/actions/post.ts
src/types/post.ts

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #216

✨ feat: 레시피 댓글 유저 이미지

---

src/app/(user)/edit/EditForm.tsx
src/app/(user)/signup/SignupForm.tsx
src/app/(user)/socialedit/SocialEditForm.tsx
src/components/common/Address.tsx
src/components/common/Dropdown.tsx

- [] 새로운 기능 추가
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
💄 style: 회원정보 수정 페이지UI 반응형
resolves #224

💄 style: 회원정보 수정 페이지UI 반응형

---

src/app/mypage/user/UserInfo.tsx
src/app/recipe/[_id]/Comment.tsx

- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
이미지 안나오는 오류 수정
resolves #247

🐛 bug: 이미지 나오도록 조건문 추가

---

src/app/mypage/layout.tsx

마이페이지 레이아웃 수정

---

src/app/mypage/recipe/myRecipe/EmptyMyRecipe.tsx
src/app/mypage/recipe/myRecipe/Loading.tsx
src/app/mypage/recipe/myRecipe/MyRecipeItem.tsx
src/app/mypage/recipe/myRecipe/MyRecipeList.tsx
src/app/mypage/recipe/myRecipe/page.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
myRecipe 대소문자 수정
resolves #

✏️ rename: myRecipe 대소문자 수정

---

src/app/recipe/[_id]/CommentNew.tsx

- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #264

🐛 bug: 배포 경로 수정

---

src/app/MainProductLists.tsx
src/app/complete/OrderNum.tsx
src/app/complete/page.tsx
src/app/page.tsx
src/data/actions/order.ts

주문 완료 페이지 주문번호 연결

---

src/app/[...not_found]/page.tsx

♻️ refactor: 이미지 경로 수정

---

src/app/recipe/[_id]/edit/page.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #

♻️ refactor: 레시피 수정 페이지 메타데이터

---

src/app/shopping/[id]/DetailInfo.tsx
src/app/shopping/[id]/Loading.tsx
src/app/shopping/[id]/page.tsx
src/app/shopping/page.tsx
src/data/functions/product.ts

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 장보기 상세 스켈레톤 UI
resolves #288

✨feat: 장보기 상세 스켈레톤 UI

---

src/app/(user)/edit/page.tsx
src/app/(user)/login/page.tsx
src/app/(user)/login/select/page.tsx
src/app/(user)/signup/page.tsx
src/app/(user)/socialedit/page.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
메타데이터 url 주소 변경
resolves #284

♻️ refactor:  메타데이터 url 주소 변경

---

src/app/mypage/recipe/bookmarkRecipe/BookmarkRecipeItem.tsx
src/app/mypage/recipe/myRecipes/MyRecipeItem.tsx

💄 style: 마이페이지 레시피 탭 말줄임 추가

---

src/app/page.tsx
src/app/recipe/RecipeCard.tsx
src/app/recipe/[_id]/page.tsx
src/app/shopping/[id]/page.tsx
src/app/shopping/page.tsx
src/app/shopping/search/[id]/page.tsx

- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 메인, 장보기 메타태그 추가
resolves #307

✨ feat: 메인, 장보기 메타태그 추가

---

src/app/recipe/RecipeCarousel.tsx
src/app/recipe/page.tsx
src/types/recipe.ts

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 인기 레시피 기준 bookmarks로 수정
resolves #311

♻️ refactor: 인기 레시피 수정

---

src/app/shopping/search/[id]/page.tsx

♻️ refactor: 빌드 에러 수정

---

src/app/recipe/[_id]/page.tsx
src/components/common/Address.tsx
src/components/common/Dropdown.tsx

로그아웃 버튼 기능 수정

---

src/app/(user)/edit/EditForm.tsx
src/app/(user)/login/LoginForm.tsx
src/app/(user)/socialedit/SocialEditForm.tsx
src/app/order/OrderForm.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
♻️ refactor: alert swal로 변경
resolves #331

♻️ refactor: alert swal로 변경

---

src/app/recipe/RecipeList.tsx
src/app/recipe/[_id]/BookmarkButton.tsx
src/app/recipe/[_id]/CommentNew.tsx
src/app/recipe/[_id]/Comments.tsx
src/app/recipe/[_id]/edit/page.tsx
src/app/recipe/[_id]/page.tsx
src/app/recipe/page.tsx
src/app/recipe/search/RecipeSearchClient.tsx
src/components/common/ShareButton.tsx

- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #329

♻️ refactor: 레시피 페이지 리팩토링

---

api/dbinit/team/data.json

📝 docs: 데이터 수정

---

api/dbinit/team/data.json
src/app/(user)/edit/EditForm.tsx
src/app/(user)/login/LoginForm.tsx
src/app/(user)/login/page.tsx
src/app/(user)/signup/SignupForm.tsx
src/app/(user)/socialedit/SocialEditForm.tsx
src/app/order/OrderUserForm.tsx

♻️ refactor: 로그인 defaultValue 추가

---

src/app/api/auth/[...nextauth]/route.ts

🐛 fix: 소셜 로그인 오류

---

src/app/api/auth/[...nextauth]/route.ts

🐛 bug: 소셜 로그인 빌드 에러

---

src/data/actions/user.ts

🐛 배포 쿠키 삭제 버그 해결

---

src/app/logout/route.ts
src/app/mypage/layout.tsx
src/components/common/Dropdown.tsx
src/data/actions/user.ts

♻️ refactor: 캐시 삭제 로직 수정

---

src/app/logout/route.ts
src/app/mypage/layout.tsx
src/components/common/Dropdown.tsx
src/data/actions/user.ts

♻️ refactor: 쿠키 삭제 로직 수정

---

src/app/logout/route.ts

쿠키 삭제 도메인 수정

---

src/app/mypage/layout.tsx
src/components/common/Dropdown.tsx

♻️ refactor: 로그아웃 로직 수정

---

src/app/editProduct/[_id]/editForm/page.tsx
src/app/mypage/product/page.tsx
src/app/mypage/product/productList.tsx
src/app/registProduct/page.tsx
src/types/product.ts

🚀 deploy: 배포
